import os
os.system("pip install pyinstaller")
os.system("pip install subprocess")
os.system("pip install sqlite3")
os.system("pip install flask")
os.system("pip install json")
os.system("pip install base64")
os.system("pip install requests")
os.system("pip install request")
os.system("pip install time")
os.system("pip install string")
os.system("pip install logging")
os.system("pip install re")
os.system("pip install time")
os.system("pip install sys")
